spring:
  datasource:
    url: jdbc:mysql://${dvp.datasource.ip}:${dvp.datasource.port}/xxzx-oauth?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
    username: ${dvp.datasource.username}
    password: ${dvp.datasource.password}
    driver-class-name: com.mysql.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.yndw.dvp.oauth.model

dvp:
  oauth2:
    token:
      store:
        type: redis
  security:
    code:
      # 忽略验证码的应用编号
      ignoreClientCode: webapp
  #审计日志
  audit-log:
    enabled: true
    log-type: db
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      jdbc-url: jdbc:mysql://${dvp.datasource.ip}:${dvp.datasource.port}/xxzx-log?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
      username: ${dvp.datasource.username}
      password: ${dvp.datasource.password}